$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    autoplay:true,
    autoplayTimeout:1700,
    autoplayHoverPause:true,
    responsive:{
        400:{
            items:2
        },
        600:{
            items:2
        },
        1000:{
            items:5
        }
    }
})
